# Generated by Django 5.2.4 on 2025-08-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='')),
                ('event_name', models.CharField(max_length=200)),
                ('event_Date', models.DateField()),
                ('event_location', models.CharField()),
                ('event_short_intro', models.CharField()),
                ('event_charges', models.CharField()),
                ('event_description', models.TextField()),
                ('event_location_extra', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='trackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='')),
                ('track_name', models.CharField(max_length=200)),
                ('track_description', models.TextField(max_length=200)),
                ('track_location', models.CharField(max_length=200)),
                ('track_location_extra', models.CharField()),
            ],
        ),
    ]
