# Generated by Django 5.2.4 on 2025-08-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='featured_image',
            field=models.ImageField(default='images/1.jpg', upload_to=''),
        ),
    ]
