# Generated by Django 5.2.4 on 2025-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_eventmodel_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='featured_image',
            field=models.ImageField(blank=True, default='1.jpg', null=True, upload_to=''),
        ),
    ]
