# Generated by Django 5.2.4 on 2025-08-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_eventmodel_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_location',
            field=models.URLField(),
        ),
    ]
