# Generated by Django 5.2.4 on 2025-08-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventmodel_event_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
