# Generated by Django 5.2.4 on 2025-08-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_eventmodel_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='event_address',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_locality',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_state',
            field=models.CharField(blank=True, null=True),
        ),
    ]
