# Generated by Django 5.2.4 on 2025-08-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_eventmodel_event_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodel',
            name='track_time',
            field=models.CharField(choices=[('1', '09:00 - 12:00'), ('2', '12:00 - 15:00'), ('3', '15:00 - 18:00')], max_length=200, null=True),
        ),
    ]
