# Generated by Django 5.2.4 on 2025-08-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trackmodel_track_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_mail', models.EmailField(max_length=200)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trackmodel',
            name='track_time',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='track_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='track_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='track_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='bookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(choices=[('1', '09:00 - 12:00'), ('2', '12:00 - 15:00'), ('3', '15:00 - 18:00')], max_length=200, null=True)),
                ('booking_status', models.BooleanField(default=True)),
                ('booking_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('booking_track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.trackmodel')),
                ('booking_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usermodel')),
            ],
        ),
    ]
