# Generated by Django 5.2.4 on 2025-08-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usermodel_remove_trackmodel_track_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='featured_image',
            field=models.ImageField(blank=True, default='noimage.svg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='featured_image',
            field=models.ImageField(default='noimage.svg', upload_to=''),
        ),
    ]
