# Generated by Django 5.2.4 on 2025-08-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_eventmodel_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='featured_image',
            field=models.ImageField(blank=True, default='noimage.svg', null=True, upload_to='eventposters/'),
        ),
    ]
