# Generated by Django 5.2.4 on 2025-08-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_eventmodel_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='event_Date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='trackmodel',
            name='track_location',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='track_map_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_time',
            field=models.CharField(choices=[('1', '09:00 - 12:00'), ('2', '12:00 - 15:00'), ('3', '15:00 - 18:00')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_charges',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_locality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_location_extra',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_short_intro',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='track_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='track_location_extra',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='featured_image',
            field=models.ImageField(default='noimage.svg', upload_to=''),
        ),
        migrations.CreateModel(
            name='eventBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_booking_status', models.BooleanField(default=True)),
                ('booking_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('event_booking_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.eventmodel')),
                ('event_booking_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usermodel')),
            ],
        ),
    ]
