# Generated by Django 5.2.4 on 2025-08-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_event_date_eventmodel_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackmodel',
            name='track_difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Intermediate'), ('3', 'Hard'), ('4', 'Very Hard'), ('5', 'Expert')], default='Easy', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='bookingmodel',
            constraint=models.UniqueConstraint(fields=('booking_track', 'booking_date', 'booking_time'), name='uniq_track_date_time_slot'),
        ),
    ]
