# Generated by Django 5.2.4 on 2025-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_trackmodel_track_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='track_difficulty',
            field=models.CharField(choices=[('Easy', '1-Easy'), ('Intermediate', '2-Intermediate'), ('Hard', '3-Hard'), ('Very Hard', '4-Very Hard'), ('Expert', '5-Expert')], default='Easy', max_length=200),
        ),
    ]
