# Generated by Django 5.2.4 on 2025-08-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_trackmodel_track_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='track_difficulty',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Intermediate'), ('3', 'Hard'), ('4', 'Very Hard'), ('5', 'Expert')], default='1', max_length=200),
        ),
    ]
