# Generated by Django 5.2.4 on 2025-08-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_trackmodel_track_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_locality',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_state',
            field=models.CharField(max_length=200),
        ),
    ]
