# Generated by Django 5.2.4 on 2025-08-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_bookingmodel_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='booking_charge',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
