# Generated by Django 5.2.4 on 2025-08-19 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bookingmodel_booking_charge'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usermodel'),
        ),
        migrations.AlterField(
            model_name='eventbookingmodel',
            name='event_booking_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.usermodel'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='track_city',
            field=models.CharField(default='City', max_length=200),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='track_locality',
            field=models.CharField(default='City', max_length=200),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='track_state',
            field=models.CharField(default='City', max_length=200),
        ),
        migrations.DeleteModel(
            name='usermodel',
        ),
    ]
