# Generated by Django 5.2.4 on 2025-09-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_bookingmodel_booking_user_and_more'),
        ('user', '0006_rename_user_name_usermodel_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel'),
        ),
    ]
