# Generated by Django 5.2.4 on 2025-08-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(default='noimage.svg', upload_to='')),
                ('user_name', models.CharField(max_length=200)),
                ('user_mail', models.EmailField(max_length=200)),
                ('user_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
