# Generated by Django 5.2.4 on 2025-08-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_first_name_usermodel_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='featured_image',
            field=models.ImageField(default='noprofile.webp', upload_to=''),
        ),
    ]
