# Generated by Django 5.2.4 on 2025-08-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_name',
            new_name='username',
        ),
    ]
