# Generated by Django 5.2.4 on 2025-08-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_name_usermodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='username',
            new_name='user_name',
        ),
    ]
