# Generated by Django 5.2.4 on 2025-09-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_username_usermodel_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
    ]
